name: Test

on: push

jobs:
  test-dotnet:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - run: dotnet test -c Debug ./VContainer.StandaloneTests

  test-unity:
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE_FILE: ./tmp/ulf
      # UNITY_BIN: xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' /opt/Unity/Editor/Unity
      UNITY_BIN: /opt/Unity/Editor/Unity
    strategy:
      matrix:
        unityVersion: ['2019.4.14f1']
        targetPlatform: ['StandaloneLinux64']
        scriptBackend: ['mono']
        include:
        - unityVersion: 2019.4.14f1
          license: UNITY_LICENSE_2019_BASE64
        # - unityVersion: 2020.1.12f1
        #   license: UNITY_LICENSE_2020_BASE64
    container:
      image: gableroux/unity3d:${{ matrix.unityVersion }}-linux-il2cpp
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: VContainer/Library
        key: Library-VContainer-${{ matrix.targetPlatform }}
        restore-keys: |
          Library-VContainer-
          Library-
    - name: Dump unity license file
      shell: bash
      run: |
        mkdir ./tmp
        mkdir ./VContainer/tmp
        chmod 777 ./VContainer/tmp
        echo -n "${{ secrets[matrix.license] }}" | base64 --decode > $UNITY_LICENSE_FILE
    - name: Load License
      shell: bash
      run: $UNITY_BIN -quit -batchmode -nographics -silent-crashes -logFile /dev/stdout -manualLicenseFile $UNITY_LICENSE_FILE || exit 0
    - name: Run Tests
      shell: bash
      run: $UNITY_BIN -batchmode -logFile /dev/stdout -projectPath ./VContainer -runTests -testResults $GITHUB_WORKSPACE/VContainer/tmp/TestResults.xml -testPlatform ${{ matrix.targetPlatform }} -scriptbackend=${{ matrix.scriptBackend }} -nographics
    - name: DEBUG
      shell: bash
      run: |
        ls -l ./tmp
        ls -l ./VContainer
        ls -l ./VContainer/tmp
    - uses: actions/upload-artifact@v1
      with:
        name: Test results
        path: ./VContainer/tmp/TestResults.xml
